version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: novamart
      POSTGRES_USER: novamart_loader
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
